// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class NativeDatastoreError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "NativeDatastoreError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeDatastoreError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class MessagesPigeonCodecReader: FlutterStandardReader {
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DatastoreApi {
  func getString(key: String, completion: @escaping (Result<String?, Error>) -> Void)
  func getBool(key: String, completion: @escaping (Result<Bool?, Error>) -> Void)
  func getInt(key: String, completion: @escaping (Result<Int64?, Error>) -> Void)
  func getDouble(key: String, completion: @escaping (Result<Double?, Error>) -> Void)
  func getStringList(key: String, completion: @escaping (Result<[String]?, Error>) -> Void)
  func setString(key: String, value: String, completion: @escaping (Result<Void, Error>) -> Void)
  func setBool(key: String, value: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func setInt(key: String, value: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func setDouble(key: String, value: Double, completion: @escaping (Result<Void, Error>) -> Void)
  func setStringList(key: String, value: [String], completion: @escaping (Result<Void, Error>) -> Void)
  func remove(key: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func clear(completion: @escaping (Result<Void, Error>) -> Void)
  func getAll(completion: @escaping (Result<[String: Any], Error>) -> Void)
  func getKeys(completion: @escaping (Result<[String], Error>) -> Void)
  func containsKey(key: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getBytes(key: String, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func setBytes(key: String, value: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func getDateTime(key: String, completion: @escaping (Result<Int64?, Error>) -> Void)
  func setDateTime(key: String, value: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func getMap(key: String, completion: @escaping (Result<String?, Error>) -> Void)
  func setMap(key: String, value: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Reads [keys] in a single call. Absent keys are omitted from the result,
  /// so the caller can distinguish "missing" from "stored null".
  func getMany(keys: [String], completion: @escaping (Result<[String: Any], Error>) -> Void)
  /// Writes every entry of [entries] in a single native transaction. Values
  /// must be String, bool, int, double or List<String>.
  func setMany(entries: [String: Any], completion: @escaping (Result<Void, Error>) -> Void)
  /// Removes [keys] in a single native transaction, returning how many were
  /// actually present.
  func removeMany(keys: [String], completion: @escaping (Result<Int64, Error>) -> Void)
  /// Atomically adds [delta] to the int at [key] (treating a missing value as
  /// 0) and returns the new value.
  func incrementInt(key: String, delta: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Atomically adds [delta] to the double at [key] (treating a missing value
  /// as 0.0) and returns the new value.
  func incrementDouble(key: String, delta: Double, completion: @escaping (Result<Double, Error>) -> Void)
  /// Atomically flips the bool at [key] (treating a missing value as false)
  /// and returns the new value.
  func toggleBool(key: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Atomically sets [key] to [value] only if its current value equals
  /// [expected] (a null [expected] means "only if absent", a null [value]
  /// means "remove"). Returns true if the swap happened.
  func compareAndSetString(key: String, expected: String?, value: String?, completion: @escaping (Result<Bool, Error>) -> Void)
  func compareAndSetInt(key: String, expected: Int64?, value: Int64?, completion: @escaping (Result<Bool, Error>) -> Void)
  func compareAndSetDouble(key: String, expected: Double?, value: Double?, completion: @escaping (Result<Bool, Error>) -> Void)
  func compareAndSetBool(key: String, expected: Bool?, value: Bool?, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Copies existing values written by the `shared_preferences` plugin into
  /// this store. When [overwrite] is false, keys already present here are
  /// left untouched. Returns the number of keys imported.
  func migrateFromSharedPreferences(overwrite: Bool, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Configures the storage backend. Must be called before the first read or
  /// write. When [multiProcess] is true (Android) the store is opened in
  /// multi-process mode; [appGroupId], when non-null (iOS), backs storage with
  /// an App Group suite so extensions/processes sharing the group see the same
  /// data. Both default off, leaving the single-process store untouched.
  func configure(multiProcess: Bool, appGroupId: String?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DatastoreApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DatastoreApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DatastoreApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getString(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStringChannel.setMessageHandler(nil)
    }
    let getBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getBool(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBoolChannel.setMessageHandler(nil)
    }
    let getIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getInt(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getIntChannel.setMessageHandler(nil)
    }
    let getDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getDouble(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDoubleChannel.setMessageHandler(nil)
    }
    let getStringListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getStringList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getStringList(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStringListChannel.setMessageHandler(nil)
    }
    let setStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        api.setString(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setStringChannel.setMessageHandler(nil)
    }
    let setBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Bool
        api.setBool(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBoolChannel.setMessageHandler(nil)
    }
    let setIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Int64
        api.setInt(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setIntChannel.setMessageHandler(nil)
    }
    let setDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Double
        api.setDouble(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDoubleChannel.setMessageHandler(nil)
    }
    let setStringListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setStringList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStringListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! [String]
        api.setStringList(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setStringListChannel.setMessageHandler(nil)
    }
    let removeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.remove(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
    let clearChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearChannel.setMessageHandler { _, reply in
        api.clear { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
    let getAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllChannel.setMessageHandler { _, reply in
        api.getAll { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAllChannel.setMessageHandler(nil)
    }
    let getKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeysChannel.setMessageHandler { _, reply in
        api.getKeys { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getKeysChannel.setMessageHandler(nil)
    }
    let containsKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.containsKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      containsKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.containsKey(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      containsKeyChannel.setMessageHandler(nil)
    }
    let getBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBytesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getBytes(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBytesChannel.setMessageHandler(nil)
    }
    let setBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBytesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! FlutterStandardTypedData
        api.setBytes(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBytesChannel.setMessageHandler(nil)
    }
    let getDateTimeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getDateTime\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDateTimeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getDateTime(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDateTimeChannel.setMessageHandler(nil)
    }
    let setDateTimeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setDateTime\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDateTimeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Int64
        api.setDateTime(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDateTimeChannel.setMessageHandler(nil)
    }
    let getMapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getMap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getMap(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMapChannel.setMessageHandler(nil)
    }
    let setMapChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setMap\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMapChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        api.setMap(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMapChannel.setMessageHandler(nil)
    }
    /// Reads [keys] in a single call. Absent keys are omitted from the result,
    /// so the caller can distinguish "missing" from "stored null".
    let getManyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.getMany\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getManyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keysArg = args[0] as! [String]
        api.getMany(keys: keysArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getManyChannel.setMessageHandler(nil)
    }
    /// Writes every entry of [entries] in a single native transaction. Values
    /// must be String, bool, int, double or List<String>.
    let setManyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.setMany\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setManyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entriesArg = args[0] as! [String: Any]
        api.setMany(entries: entriesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setManyChannel.setMessageHandler(nil)
    }
    /// Removes [keys] in a single native transaction, returning how many were
    /// actually present.
    let removeManyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.removeMany\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeManyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keysArg = args[0] as! [String]
        api.removeMany(keys: keysArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeManyChannel.setMessageHandler(nil)
    }
    /// Atomically adds [delta] to the int at [key] (treating a missing value as
    /// 0) and returns the new value.
    let incrementIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.incrementInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      incrementIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let deltaArg = args[1] as! Int64
        api.incrementInt(key: keyArg, delta: deltaArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      incrementIntChannel.setMessageHandler(nil)
    }
    /// Atomically adds [delta] to the double at [key] (treating a missing value
    /// as 0.0) and returns the new value.
    let incrementDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.incrementDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      incrementDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let deltaArg = args[1] as! Double
        api.incrementDouble(key: keyArg, delta: deltaArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      incrementDoubleChannel.setMessageHandler(nil)
    }
    /// Atomically flips the bool at [key] (treating a missing value as false)
    /// and returns the new value.
    let toggleBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.toggleBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.toggleBool(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      toggleBoolChannel.setMessageHandler(nil)
    }
    /// Atomically sets [key] to [value] only if its current value equals
    /// [expected] (a null [expected] means "only if absent", a null [value]
    /// means "remove"). Returns true if the swap happened.
    let compareAndSetStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.compareAndSetString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compareAndSetStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let expectedArg: String? = nilOrValue(args[1])
        let valueArg: String? = nilOrValue(args[2])
        api.compareAndSetString(key: keyArg, expected: expectedArg, value: valueArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compareAndSetStringChannel.setMessageHandler(nil)
    }
    let compareAndSetIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.compareAndSetInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compareAndSetIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let expectedArg: Int64? = nilOrValue(args[1])
        let valueArg: Int64? = nilOrValue(args[2])
        api.compareAndSetInt(key: keyArg, expected: expectedArg, value: valueArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compareAndSetIntChannel.setMessageHandler(nil)
    }
    let compareAndSetDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.compareAndSetDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compareAndSetDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let expectedArg: Double? = nilOrValue(args[1])
        let valueArg: Double? = nilOrValue(args[2])
        api.compareAndSetDouble(key: keyArg, expected: expectedArg, value: valueArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compareAndSetDoubleChannel.setMessageHandler(nil)
    }
    let compareAndSetBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.compareAndSetBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compareAndSetBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let expectedArg: Bool? = nilOrValue(args[1])
        let valueArg: Bool? = nilOrValue(args[2])
        api.compareAndSetBool(key: keyArg, expected: expectedArg, value: valueArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compareAndSetBoolChannel.setMessageHandler(nil)
    }
    /// Copies existing values written by the `shared_preferences` plugin into
    /// this store. When [overwrite] is false, keys already present here are
    /// left untouched. Returns the number of keys imported.
    let migrateFromSharedPreferencesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.migrateFromSharedPreferences\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      migrateFromSharedPreferencesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let overwriteArg = args[0] as! Bool
        api.migrateFromSharedPreferences(overwrite: overwriteArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      migrateFromSharedPreferencesChannel.setMessageHandler(nil)
    }
    /// Configures the storage backend. Must be called before the first read or
    /// write. When [multiProcess] is true (Android) the store is opened in
    /// multi-process mode; [appGroupId], when non-null (iOS), backs storage with
    /// an App Group suite so extensions/processes sharing the group see the same
    /// data. Both default off, leaving the single-process store untouched.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.DatastoreApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let multiProcessArg = args[0] as! Bool
        let appGroupIdArg: String? = nilOrValue(args[1])
        api.configure(multiProcess: multiProcessArg, appGroupId: appGroupIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
  }
}
/// Secure-storage host API. Implementations encrypt data at rest using
/// platform key management (Keychain on iOS, AndroidKeyStore-backed AES-GCM
/// over DataStore on Android). Only string and bytes are supported — callers
/// that need richer types should serialize first.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureDatastoreApi {
  func getString(key: String, completion: @escaping (Result<String?, Error>) -> Void)
  func setString(key: String, value: String, completion: @escaping (Result<Void, Error>) -> Void)
  func getBytes(key: String, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func setBytes(key: String, value: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func remove(key: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func clear(completion: @escaping (Result<Void, Error>) -> Void)
  func getKeys(completion: @escaping (Result<[String], Error>) -> Void)
  func containsKey(key: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Configures the secure storage backend. Must be called before the first
  /// read or write. When [multiProcess] is true (Android) the encrypted store
  /// is opened in multi-process mode; [appGroupId], when non-null (iOS), is
  /// used as the Keychain access group so extensions/processes sharing it see
  /// the same secrets. Both default off, leaving the single-process store
  /// untouched.
  func configure(multiProcess: Bool, appGroupId: String?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureDatastoreApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SecureDatastoreApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureDatastoreApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.getString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getString(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStringChannel.setMessageHandler(nil)
    }
    let setStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.setString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        api.setString(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setStringChannel.setMessageHandler(nil)
    }
    let getBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.getBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBytesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getBytes(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBytesChannel.setMessageHandler(nil)
    }
    let setBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.setBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBytesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! FlutterStandardTypedData
        api.setBytes(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBytesChannel.setMessageHandler(nil)
    }
    let removeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.remove(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
    let clearChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearChannel.setMessageHandler { _, reply in
        api.clear { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
    let getKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.getKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeysChannel.setMessageHandler { _, reply in
        api.getKeys { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getKeysChannel.setMessageHandler(nil)
    }
    let containsKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.containsKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      containsKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.containsKey(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      containsKeyChannel.setMessageHandler(nil)
    }
    /// Configures the secure storage backend. Must be called before the first
    /// read or write. When [multiProcess] is true (Android) the encrypted store
    /// is opened in multi-process mode; [appGroupId], when non-null (iOS), is
    /// used as the Keychain access group so extensions/processes sharing it see
    /// the same secrets. Both default off, leaving the single-process store
    /// untouched.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_datastore.SecureDatastoreApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let multiProcessArg = args[0] as! Bool
        let appGroupIdArg: String? = nilOrValue(args[1])
        api.configure(multiProcess: multiProcessArg, appGroupId: appGroupIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
  }
}
